apiVersion: v1
kind: Service
metadata:
  name: pyflask-service
spec:
  selector:
    app: pyflask
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pyflask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyflask
  template:
    metadata:
      labels:
        app: pyflask
    spec:
      containers:
      - name: pyflask
        image: sasi1081/pythonflask:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
